# Generated by Django 4.1 on 2022-08-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speedtests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="provider",
            field=models.CharField(
                choices=[("Ookla", "Ookla"), ("LibreSpeed", "LibreSpeed")],
                default="Ookla",
                max_length=32,
            ),
        ),
    ]
