# Generated by Django 4.1 on 2022-08-12 06:08

from django.db import migrations, models


def create_server_ids(apps, schema_editor):
    ServerList = apps.get_model("speedtests", "ServerList")
    for server_list in ServerList.objects.all():
        r = []
        for server in server_list.servers.all():
            r.append(server.pk)
        server_list.detail = {"server_ids": r}
        server_list.save()


class Migration(migrations.Migration):

    dependencies = [
        ("speedtests", "0002_alter_server_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverlist",
            name="detail",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(create_server_ids, migrations.RunPython.noop),
    ]
