# Generated by Django 4.1 on 2022-08-20 06:41

from django.db import migrations

def add_url(apps, schema_editor):
    import json
    data = None
    with open("url_data.json") as f:
        data = json.load(f)

    Server = apps.get_model("speedtests", "Server")
    for server in Server.objects.all():
        if server.provider == "Ookla":
            pk = str(server.pk)
            url = data[pk]
            download_url = f"{url}/download"
            upload_url = f"{url}/upload"
        else:
            s = server.detail['server']
            dl_url = server.detail['dlURL']
            ul_url = server.detail['ulURL']
            if s.startswith("//"):
                s = f"https:{s}"
            if not s.endswith("/"):
                s = f"{s}/"
            download_url = f"{s}{dl_url}"
            upload_url = f"{s}{ul_url}"
        server.detail.update({
                "dl": download_url,
                "ul": upload_url
            })
        server.save()


class Migration(migrations.Migration):

    dependencies = [
        ("speedtests", "0005_auto_20220817_0611"),
    ]

    operations = [
        migrations.RunPython(add_url, migrations.RunPython.noop),
    ]
