# Generated by Django 4.1 on 2022-08-23 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("speedtests", "0006_auto_20220820_0641"),
    ]

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("ip", models.GenericIPAddressField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_results",
                        related_query_name="server_result",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MachineTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Wait", "Wait"),
                            ("Work", "Work"),
                            ("Finish", "Finish"),
                        ],
                        default="Wait",
                        max_length=32,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("oneshot", models.BooleanField()),
                ("detail", models.JSONField()),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        related_query_name="task",
                        to="speedtests.machine",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="serverresult",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="serverresult",
            name="server",
        ),
        migrations.RemoveField(
            model_name="serverresult",
            name="server_list_result",
        ),
        migrations.DeleteModel(
            name="ServerListResult",
        ),
        migrations.DeleteModel(
            name="ServerResult",
        ),
    ]
