[package]
name = "bim-server"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "api", "entity", "migration", "service"]

[dependencies]
server-api = { path = "api" }


[profile.release]
strip = true
lto = true
codegen-units = 1
