# Generated by Django 5.0.7 on 2024-07-24 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('nickname', models.CharField(default='XXX', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.URLField(db_index=True)),
                ('ipv6', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TcpPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ping_min', models.FloatField(blank=True, null=True)),
                ('ping_jitter', models.FloatField(blank=True, null=True)),
                ('ping_failed', models.SmallIntegerField(default=0)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tcp_pings', related_query_name='tcp_ping', to='rounds.machine')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tcp_pings', related_query_name='tcp_ping', to='rounds.target')),
            ],
        ),
    ]
