# Generated by Django 4.1.7 on 2023-03-26 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=16)),
                ("ip", models.GenericIPAddressField(db_index=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Ready", "Ready"),
                            ("Working", "Working"),
                            ("Offline", "Offline"),
                        ],
                        default="Ready",
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=16)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("download_url", models.URLField()),
                ("upload_url", models.URLField()),
                ("ipv6", models.BooleanField(default=False)),
                ("multi", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Block", "Block"),
                            ("Ready", "Ready"),
                            ("Finish", "Finish"),
                            ("Timeout", "Timeout"),
                        ],
                        default="Block",
                        max_length=16,
                    ),
                ),
                ("download", models.FloatField(default=0)),
                ("download_status", models.CharField(default="", max_length=16)),
                ("upload", models.FloatField(default=0)),
                ("upload_status", models.CharField(default="", max_length=16)),
                ("latency", models.FloatField(default=0)),
                ("jitter", models.FloatField(default=0)),
                (
                    "machine",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        related_query_name="task",
                        to="servers.machine",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        related_query_name="task",
                        to="servers.server",
                    ),
                ),
            ],
        ),
    ]
