# Generated by Django 4.2 on 2023-05-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="nickname",
            field=models.CharField(default="XXX", max_length=32),
        ),
        migrations.AlterField(
            model_name="machine",
            name="ip",
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name="machine",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
