name: Build

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross

      - name: Build ${{ matrix.target }}
        timeout-minutes: 15
        run: |
          mkdir -p ./build/release
          cross build --target ${{ matrix.target }} --release
          cp ./target/${{ matrix.target }}/release/bim-server ./build/release/bim-server

      - name: UPX
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          files: ./build/release/bim-server
          args: --best --lzma

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bim-${{ matrix.target }}
          path: build/release/bim-server

  build-windows:
    runs-on: windows-latest
    env:
      RUST_BACKTRACE: full

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Build
        timeout-minutes: 15
        run: |
          cargo build --release
          mkdir -p ./build/release
          cp ./target/release/bim-server.exe ./build/release/bim-server.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bim-server-windows
          path: build/release/bim-server.exe

  build-macos:
    runs-on: macos-latest
    env:
      RUST_BACKTRACE: full

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Build
        timeout-minutes: 120
        run: |
          cargo build --release
          mkdir -p ./build/release
          cp ./target/release/bim-server ./build/release/bim-server

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bim-server-macos
          path: build/release/bim-server
